#!/usr/bin/python

"""Amulet tests on a basic nova compute deployment on utopic-juno."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='utopic')
    deployment.run_tests()
