#!/usr/bin/python

"""Amulet tests on a basic nova compute deployment on precise-folsom."""

import amulet
from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    # NOTE(coreycb): Skipping failing test until resolved. 'nova-manage db sync'
    #                fails in shared-db-relation-changed (only fails on folsom)
    message = "Skipping failing test until resolved"
    amulet.raise_status(amulet.SKIP, msg=message)

    deployment = NovaBasicDeployment(series='precise',
                                     openstack='cloud:precise-folsom',
                                     source='cloud:precise-updates/folsom')
    deployment.run_tests()
