#!/usr/bin/python

"""Amulet tests on a basic nova compute deployment on precise-grizzly."""

from basic_deployment import NovaBasicDeployment

if __name__ == '__main__':
    deployment = NovaBasicDeployment(series='precise',
                                     openstack='cloud:precise-grizzly',
                                     source='cloud:precise-updates/grizzly')
    deployment.run_tests()
